// Public wire constants only. Never import secrets, signing, or SDK clients here.
export const SIGNAL_SCHEMA_VERSION = 1;
export const SIGNAL_NAMESPACE = "RU_FOMO";
export const SOL_MINT = "So11111111111111111111111111111111111111112";
export const SIGNAL_STATUSES = ["dry_run", "rejected", "submitted", "confirmed", "failed", "unknown"];
export const SIGNAL_CODES = [
  "DRY_RUN", "SUBMITTED", "CONFIRMED", "CONFIG_INVALID", "DISABLED",
  "AUTH_REQUIRED", "RATE_LIMITED", "STALE_DATA", "SLIPPAGE_EXCEEDED",
  "SIMULATION_FAILED", "TRANSACTION_REJECTED", "INSUFFICIENT_SOL",
  "BUDGET_EXCEEDED", "EXPIRED_SIGNAL", "DUPLICATE_SIGNAL", "PROVIDER_ERROR",
  "RPC_ERROR", "CONFIRMATION_UNKNOWN", "INVALID_SIGNAL", "PROGRAM_NOT_ALLOWED",
  "REPORT_FAILED", "INTERNAL_ERROR", "TOKEN_NOT_ALLOWED", "UNSUPPORTED_POOL",
];